---
# tasks file for kiosk_mode
- name: Ensure hostname set
  hostname:
    name: {{ inventory_hostname }}

- name: Register as user with password and auto-subscribe to available content.
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: true

- name: install Gnome Desktop Environment
  ansible.builtin.yum:
    name: "@Server With GUI"
    state: present

- name: Create gdm configuration for kiosk kiosk_mode
  ansible.builtin.template:
    src: custom.conf
    dest: /etc/gdm/custom.conf
    mode: 0644

- name: Add the user 'kiosk' 
  ansible.builtin.user:
    name: kiosk
    comment: kiosk user
    state: present
    shell: /bin/bash
    uid: 2000
    group: users

- name: configure session for kiosk username /var/lib/AccountsService/users/kiosk
  ansible.builtin.template:
    src: kiosk.conf
    dest: /var/lib/AccountsService/users/kiosk
    mode: 0644
  
- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled

- name: install yum install gnome-shell-extension-desktop-icons so we can put icon on desktop
  ansible.builtin.yum:
    name: gnome-shell-extension-desktop-icons
    state: present

- name: create directory local bin for kiosk mode
  ansible.builtin.file:
    path: /home/kiosk/.local/bin
    state: directory
    mode: 0755

- name: create directory local bin for kiosk mode
  ansible.builtin.file:
    path: /home/kiosk/Desktop
    state: directory
    mode: 0755

- name: create shell script to start firefox
  ansible.builtin.copy:
    dest: /home/kiosk/.local/bin/redhat-kiosk
    src: files/redhat-kiosk
    mode: 775
    owner: kiosk

- name: create desktop icon for Ignition Kiosk
  ansible.builtin.copy:
    dest: /home/kiosk/Desktop/kiosk.desktop
    src: files/kiosk.desktop
    mode: 775
    owner: kiosk

- name: reboot the machine with all defaults to deploy the changes
  reboot:
