---
- name: Automember group present example
  hosts: ipaserver
  become: true
  tasks:
  - name: Ensure group automember rule admins is present
    redhat.rhel_idm.ipaautomember:
      ipaadmin_password: SomeADMINpassword
      name: admins
      automember_type: group
      state: present
