---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure host server is present in HBAC Rule allhosts
    redhat.rhel_idm.ipahbacrule:
      ipaadmin_password: SomeADMINpassword
      name: allhosts
      host: server
      action: member
