---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure HBAC Rule allhosts is enabled
    redhat.rhel_idm.ipahbacrule:
      ipaadmin_password: SomeADMINpassword
      name: allhosts
      state: enabled
