---
- name: Install IPA servers
  hosts: ipaserver
  become: true

  roles:
  - role: redhat.rhel_idm.ipaserver
    state: present

- name: Install IPA replicas
  hosts: ipareplicas
  become: true

  roles:
  - role: redhat.rhel_idm.ipareplica
    state: present

- name: Install IPA clients
  hosts: ipaclients
  become: true

  roles:
  - role: redhat.rhel_idm.ipaclient
    state: present
