---
- name: Uninstall IPA clients
  hosts: ipaclients
  become: true

  roles:
  - role: redhat.rhel_idm.ipaclient
    state: absent

- name: Uninstall IPA replicas
  hosts: ipareplicas
  become: true

  roles:
  - role: redhat.rhel_idm.ipareplica
    state: absent

- name: Uninstall IPA servers
  hosts: ipaserver
  become: true

  roles:
  - role: redhat.rhel_idm.ipaserver
    state: absent
