---
- name: Playbook to disallow reverse record synchronization.
  hosts: ipaserver
  become: true

  tasks:
  - name: Disallow reverse record synchronization.
    redhat.rhel_idm.ipadnsconfig:
      allow_sync_ptr: no
