---
- name: dnszone present
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure zone is present.
    redhat.rhel_idm.ipadnszone:
      ipaadmin_password: SomeADMINpassword
      name: testzone.local
      state: present
