---
- name: Playbook to handle groups
  hosts: ipaserver
  become: true

  tasks:
  - name: Create group ops with gid 1234
    redhat.rhel_idm.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: ops
      gidnumber: 1234

  - name: Create group sysops
    redhat.rhel_idm.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: sysops
      user:
      - pinky

  - name: Create group appops
    redhat.rhel_idm.ipagroup:
      ipaadmin_password: SomeADMINpassword
      name: appops
