---
- name: Playbook to handle users
  hosts: ipaserver
  become: true

  tasks:
  - name: Enable user pinky
    redhat.rhel_idm.ipauser:
      ipaadmin_password: SomeADMINpassword
      name: pinky
      state: enabled
