---
- name: Selfservice member present
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure selfservice "basic manager attributes" member attribute departmentnumber is present
    redhat.rhel_idm.ipaselfservice:
      ipaadmin_password: SomeADMINpassword
      name: "basic manager attributes"
      attribute:
      - departmentnumber
      action: member
