---
- name: Playbook to handle global DNS configuration
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
  - name: Query IPA global configuration
    redhat.rhel_idm.ipaconfig:
      ipaadmin_password: SomeADMINpassword
    register: serverconfig

  - name: Display current configuration.
    debug:
      msg: "{{ serverconfig }}"
