---
- name: Playbook to handle hostgroups
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure host-group databases is present
    redhat.rhel_idm.ipahostgroup:
      ipaadmin_password: SomeADMINpassword
      name: databases
      host:
      - db.example.com
      hostgroup:
      - mysql-server
      - oracle-server
