---
- name: Playbook to change password of symmetric vault.
  hosts: ipaserver
  become: yes
  gather_facts: no

  tasks:
  - name: Create vault.
    redhat.rhel_idm.ipavault:
      ipaadmin_password: SomeADMINpassword
      name: symvault
      password: SomeVAULTpassword
  - name: Change vault password.
    redhat.rhel_idm.ipavault:
      ipaadmin_password: SomeADMINpassword
      name: symvault
      password: SomeVAULTpassword
      new_password: SomeNEWpassword
