---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure shared vault is absent.
    redhat.rhel_idm.ipavault:
      ipaadmin_password: SomeADMINpassword
      name: sharedvault
      shared: True
      state: absent
