---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Ensure vault member "user" is present.
    redhat.rhel_idm.ipavault:
      ipaadmin_password: SomeADMINpassword
      name: keychain
      username: admin
      state: present
      action: member
      users: user1
