---
- name: Create a virtual machine from a template
  vmware_guest:
    esxi_hostname: "{{ esxi_hostname }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    folder: "{{ vcsa_folder }}"
    name: "{{ host_hostname }}"
    state: poweredon
    template: "{{ host_template }}"
    disk:
    - size_gb: "{{ host_disk_size }}"
      type: "{{ host_disk_type }}"
      datastore: "{{ esxi_datastore }}"
  vars:
    vmware:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'