---
- name: Configure Fedora Workstation
  hosts: localhost
  gather_facts: False
  become: no
  roles:
    - vmware

  vars:
    vmware:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'