---
- name: Privilege absent example
  hosts: ipaserver
  become: true

  tasks:
  - name: Ensure privilege "Broad Privilege" is absent
    redhat.rhel_idm.ipaprivilege:
      name: Broad Privilege
      state: absent
